### ISSUE TITLE
the questions about gpu

### ISSUE THREAD

**Issue by hero-y** [justimyhxu/Dense-RepPoints#3]
Hello, the densereppoint is good work. Can you tell me which GPU do you use in the configs "dense_reppoints_729pts_r50_fpn_1x". I want to use 2080ti GPU to train, but it shows that it doesn't have enough capacity, so how can I modify the configs to achieve the same result with origin parameters, and which GPU do you use？Thank you!

**Comment by justimyhxu** [comment]
Hi,
Our experiments are conducted on 8 V100 GPUS, but recently I also reproduced the reported results on my Titan-X machine, whose memory is nearly as same as 2080ti. If it doesn't have enough capacity on your 2080ti machine, you can add `with_cp=True`  to the backbone config to save memory.
```
backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=True),
        with_cp=True,
        style='pytorch')
```
