### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by hero-y** [justimyhxu/Dense-RepPoints#4]
Hello, I have tried the code about the configs "dense_reppoints_729pts_r50_fpn_1x", I found the model speed is a bit slow when tested on p100 gpu，just 1.2 fps.
So how can I modify the configs to achieve a similar result and improve speed？
Can you give me some data results when using fewer key points？
Can you tell me which conference this article was voted for？
Looking forward to your reply，Thank you！

**Comment by hero-y** [comment]
Hello, when I set num_points to 225, during training, the loss will become nan, what could it cause? Do I need to modify the num_score_group parameter, or other parameters?
Looking forward to your reply, thank you!

**Comment by xiaoxiaoxh** [comment]
Hi,
We will optimize our code to improve speed in the future. More results and models will be released soon. We will also update our arXiv paper. The NaN loss might be resulted by chamfer loss. If you want to use num_points fewer than 441, you need to set `use_cuda=False` in `loss_pts_init` and `loss_pts_refine`.  Here is an example:
`loss_pts_init=dict(type='ChamferLoss2D', use_cuda=False, loss_weight=0.5)
 loss_pts_refine=dict(type='ChamferLoss2D', use_cuda=False, loss_weight=1.0)`

**Comment by laisimiao** [comment]
@xiaoxiaoxh Could I ask why are there so many 'del' operations in codes?
Looking forward to your reply，Thank you！

**Comment by laisimiao** [comment]
> Hi,
> We will optimize our code to improve speed in the future. More results and models will be released soon. We will also update our arXiv paper. The NaN loss might be resulted by chamfer loss. If you want to use num_points fewer than 441, you need to set `use_cuda=False` in `loss_pts_init` and `loss_pts_refine`. Here is an example:
> `loss_pts_init=dict(type='ChamferLoss2D', use_cuda=False, loss_weight=0.5) loss_pts_refine=dict(type='ChamferLoss2D', use_cuda=False, loss_weight=1.0)`

What's the reason of ` If you want to use num_points fewer than 441, you need to set use_cuda=False`? Could you please point out the original address of this requirement?
BTW, have you tried [GeomLoss](http://www.kernel-operations.io/geomloss/index.html) implementation to carry out 'ChamferLoss2D'? Does it also work?
